[package]
name = "pixiv-cli-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Rust CLI derived from pixiv-cli"
publish = false

[[bin]]
name = "pixiv"
path = "src/main.rs"

[dependencies]
clap.workspace = true
pixiv-sdk = { path = "../pixiv-sdk" }
serde_json.workspace = true
tokio.workspace = true
