[package]
name = "pixiv-record"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
pixiv-sdk = { path = "../pixiv-sdk" }
serde_json.workspace = true

[dev-dependencies]
serde.workspace = true
tokio.workspace = true
