# pixiv-cli configuration
# Use "pixiv config set KEY VALUE" to change a setting.

[download]
path = "./downloads"
filename_template = "{author} - {title}_{id}"

[output]
json = false

[login]
open_browser = true
use_after_login = false

[update]
check_enabled = true

[logging]
level = "info"
format = "text"

[reverse_search]
provider = "saucenao"
pixiv_only = true
